---
# tasks file for xldeploy
- name: Installing boto.
  pip:
    name: boto

- name: Launch instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ keypair }}"
    group_id: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    user_data: |
      #!/bin/bash
      yum install wget -y
      yum install epel-release -y
      yum install ansible -y
      wget -O- https://get.docker.com/ | sh
      systemctl status docker
      systemctl start docker
      systemctl enable docker
      systemctl status docker
      systemctl status -l docker
      yum install -y docker-compose
      docker run -e "ADMIN_PASSWORD=bhemanth" -e "ACCEPT_EULA=Y" -p 4516:4516 --name xld xebialabs/xl-deploy:9.0
    wait: true
    wait_timeout: 500
    instance_tags:
      Name: xldeploy
      Environment: Production
    region: "{{ region }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ volume_size }}"
        delete_on_termination: true
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: true
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"
